#!/usr/bin/env python
# encoding: UTF-8

# Silence warnings
import psychopy.logging
psychopy.logging.console.setLevel(psychopy.logging.CRITICAL)

import schizoidpy
from schizoidpy import StimGroup, TriggerKey
from psychopy.visual import TextStim, ImageStim, Rect, Circle
from psychopy.visual.ratingscale import RatingScale
from psychopy.core import CountdownTimer
from random import random, lognormvariate, expovariate, sample
from collections import Counter
from cgi import escape
from sys import argv

par = dict(zip(argv[1::2], argv[2::2])) # DEPLOYMENT SCRIPT EDITS THIS LINE

o = schizoidpy.Task(
    debug_log_dir = par['debug_log_dir'],
    send_actiview_trigger_codes = par['eeg'],
    inpout32_addr = par['inpout32_addr'],
    double_draw = par['double_draw'],
    button_radius = .12,
    okay_button_pos = (0, -.7),
    bg_color = 'black', fixation_cross_color = 'white')
o.save('task_version', par['task_version'])

# ------------------------------------------------------------
# * Data
# ------------------------------------------------------------

male_names = {'PLACEHOLDER male 1', 'Ben', 'Christian', 'Darin', 'Jack', 'Liam', 'Trevor'}
extra_male_name = 'Noah'
female_names = {'PLACEHOLDER female 1', 'Alexis', 'Anna', 'Brianna', 'Gabrielle', 'Julia', 'Margaret'}
extra_female_name = 'Faith'
portrait_dims = (144, 216)
male_portraits = {'example-male.png', 'klein-age15-m-1.jpg', 'klein-age15-m-4.jpg', 'klein-age15-m-7.jpg', 'klein-age15-m-8.jpg', 'm-hispanic-smiling-blue-messyhair.jpg', 'm-white-smiling-black.jpg', 'shankman-m-adult-1.jpg', 'kujawa-m-1.jpg'}
female_portraits = {'example-female.png'}.union('klein-age15-f-{}.jpg'.format(i + 1) for i in range(7))
locations = {
    # Schools with "University" in the name are special. They can
    # only be assigned to 18-year-olds.
    ('PLACEHOLDER city 1', 'PLACEHOLDER school 1'),
    ('PLACEHOLDER city 2', 'PLACEHOLDER school 2'),
    ('Pasadena, CA', 'Pasadena High School'),
    ('Chicago, IL', 'UIC College Prep'),
    ('St. Louis, MO', 'Washington University'),
    ('Notre Dame, IN', 'University of Notre Dame'),
    ('Pittsburgh, PA', 'Taylor Allderdice High School'),
    ('Ocean City, NJ', 'Ocean City High School'),
    ('Saint Paul, MN', 'Central High School'),
    ('Euclid, OH', 'Andrews Osborne Academy'),
    ('Westbrook, ME', 'Westbrook High School'),
    ('Allen, TX', 'Coram Deo Academy'),
    ('San Jose, CA', 'Bellarmine College Prep')}

interests = {
    'PLACEHOLDER',
    'theater',
    'Drawing and painting',
    'fishing or anything outdoors',
    'Instagram, twitter',
    'listening to music and watching netflix',
    'Minecraft, videogames',
    'pretty much any sport',
    'Relaxing on the beach',
    'Shopping with friends',
    'skateboarding',
    'Sleeping',
    'soccer!!'}
ages = map(str, [
    1, 1, # PLACEHOLDERS
    14,
    15, 15,
    16, 16, 16,
    17, 17, 17,
    18, 18])

round_descriptions = [
    dict(place = 'Kauai',
        background = 'Hanalei,_Kauai_HI.jpg',
        fluff = "Welcome to Kauai, the geologically oldest of the Hawaiian Islands! You are getting closer to the Big Island of Hawaii. Let's play another round.",
        question = "Who's your favorite singer or musical group?",
        responses = ['PLACEHOLDER a11', 'PLACEHOLDER a12', 'Jason Aldean', 'Childish Gambino', 'Drake', 'Ed Sheeran', 'Fall Out Boy', 'fetty wap', 'Grateful Dead', 'Grimes', 'J. Cole', 'Luke Bryan', 'The Weeknd', 'wiz khalifa']),
    dict(place = 'Oahu',
        background = 'Sunset_next_to_Waikiki_Beach,_Oahu,_Hawai,_USA1.jpg',
        fluff = "Welcome to Oahu, the third-largest of the Hawaiian Islands! You are getting closer and closer to the Big Island. Let's play another round.",
        question = "What's your least favorite thing to do (that you have to do anyway)?",
        responses = ['PLACEHOLDER a21', 'PLACEHOLDER a22', 'babysit my bro and sis', 'Class presentations', 'Clean my room', 'study', 'Going to the orthodontist', 'Exercise', 'math homework', 'Take out the garbage', 'Wake up early']),
    dict(place = 'Molokai',
        background = 'Church_at_the_end_of_the_road.jpg',
        fluff = "Welcome to Molokai, an island built from two shield volcanoes and one step closer to the Big Island. Let's play again.",
        question = 'If you could bring only one thing to a desert island, what would it be?',
        responses = ['PLACEHOLDER a31', 'PLACEHOLDER a32', 'A boat', 'Computer', 'iphone', 'My best friend', 'My dog', 'My phone', 'Pizza', 'swiss army knife']),
    dict(place = 'Lanai',
        background = 'Full_moon_setting_over_Lanai.jpg',
        fluff = "Welcome to Lanai, a comma-shaped island that was once covered with pineapple plantations. You're the nearest you've come to the Big Island yet, but which of you will make it there? Let's play another round.",
        question = "What's your favorite class in school?",
        responses = ['PLACEHOLDER a41', 'PLACEHOLDER a42', 'Art', 'Music', 'Bio', 'English', 'graphic design', 'Lunch', 'Social Studies', 'Spanish', 'Math']),
    dict(place = 'Maui',
        background = 'Kipahulu_coast.jpg',
        fluff = "Welcome to Maui, the second-largest of the Hawaiian Islands! You're almost there! Let's play again to see who will make it to the Big Island of Hawaii.",
        question = "If you could have a super power, what would it be?",
        responses = ['PLACEHOLDER a51', 'PLACEHOLDER a52', 'Ability to kill zombies', 'Flying', 'Mind control', 'mind reading', 'Shape shifting', 'Super strength', 'Time travel'])]

round_wait = 2

# The format of EEG trigger codes is as follows:
#
# Bits 0–2: Encodes the type of event.
events = dict(
    # We skip 0 because that's a control code.
    subject_votes_to_accept   = 0b00000001,
    subject_votes_to_reject   = 0b00000010,
    subject_votes_neutral     = 0b00000011,
    subject_gets_accept_vote  = 0b00000100,
    subject_gets_reject_vote  = 0b00000101,
    subject_gets_neutral_vote = 0b00000110)
# Bit 3: Encodes coplayer gender (0 male, 1 female).
# Bits 4–6: Encodes the coplayer involved in the event. These
#   ID numbers are gender-specific (e.g., male coplayer 3 and
#   female coplayer 3 are different coplayers).
# Bit 7: Always 0, avoiding confusion with codes 255 and 256
#   (which are more control codes).
def trigger_code(coplayer, event):
    return (
        (coplayer['trigger_id'] << 4) |
        (coplayer['female'] << 3) |
        events[event])

# ------------------------------------------------------------
# * Helper functions
# ------------------------------------------------------------

def shuffled(x): return sample(x, len(x))
def choice(x): return shuffled(x)[0]
  # random.choice doesn't work on sets.

def image_path(image):
    return par['image_dir'] + image

big_canvas = Rect(o.win,
    width = 1.5, height = 1.8,
    fillColor = 'white', opacity = .8)
strip_canvas = Rect(o.win,
    width = 1.2, height = .3,
    fillColor = 'white', opacity = .8)
background_imagestim = ImageStim(o.win,
    image_path('Niihau_sep_2007.jpg'),
    units = 'pix',
    size = [o.screen_width, o.screen_height])

def background(image_name):
    background_imagestim.setImage(image_path(image_name))
    return o.showing(background_imagestim, big_canvas)

def message(duration, string):
    # Temporarily replace big_canvas with strip_canvas.
    with o.hiding(big_canvas):
        o.wait_screen(duration,
            strip_canvas,
            o.text(0, 0, string, wrap = 1.2))

blank_background = o.hiding(background_imagestim, big_canvas)

def lag(duration):
    message(duration, u'Waiting for all players to finish…')

def write(write_point):
    # Don't use o.save in case we're inside a `dkey_prefix`.
    o.data['write_point'] = write_point
    p = par['output_path_fmt'].format(**o.data)
    o.write(p, json_default = json_default)
    print 'Data written to', p

def json_default(x):
    if x is Reject:
        return -1
    elif x is Neutral:
        return 0
    elif x is Accept:
        return 1
    else:
        raise TypeError

def simplify_gender(gender):
  # When the text string `gender` clearly identifies a binary gender,
  # return "Male" or "Female". Otherwise, just normalize capitalization.
    g = gender.lower()
    if g in ['m', 'male', 'b', 'boy', 'man']:
        return 'Male'
    if g in ['f', 'female', 'g', 'girl', 'w', 'woman']:
        return 'Female'
    return gender[0].upper() + gender[1:].lower()

# ------------------------------------------------------------
# * Coplayers
# ------------------------------------------------------------

class VoteType(object):
    def __init__(self, letter):
        self.letter = letter
    def __str__(self):
        return self.letter
Reject = VoteType('R')
Reject.key = 'f'
Neutral = VoteType('N')
Accept = VoteType('A')
Accept.key = 'j'

coplayers = dict(

    mean3 = dict(expendable = False,
        votes = (Reject, Reject, Reject, Neutral, Reject, Reject)),
    mean2 = dict(expendable = False,
        votes = (Reject, Reject, Neutral, Reject, Reject, Neutral)),
    mean1 = dict(expendable = False,
        votes = (Neutral, Reject, Reject, Accept, Reject, Neutral)),
    indiff = dict(expendable = False,
        votes = (Neutral, Neutral, Neutral, Reject, Accept, Neutral)),
    nice1 = dict(expendable = False,
        votes = (Accept, Neutral, Accept, Accept, Neutral, Reject)),
    nice2 = dict(expendable = False,
        votes = (Accept, Accept, Accept, Neutral, Neutral, Accept)),
    nice3 = dict(expendable = False,
        votes = (Accept, Accept, Neutral, Accept, Accept, Accept)),

    xpendable_rna = dict(expendable = True,
        votes = (Reject, Neutral, Accept, Reject, Neutral, Accept)),
    xpendable_ran = dict(expendable = True,
        votes = (Reject, Accept, Neutral, Reject, Accept, Neutral)),
    xpendable_nra = dict(expendable = True,
        votes = (Neutral, Reject, Accept, Neutral, Reject, Accept)),
    xpendable_nar = dict(expendable = True,
        votes = (Neutral, Accept, Reject, Neutral, Accept, Reject)),
    xpendable_arn = dict(expendable = True,
        votes = (Accept, Reject, Neutral, Accept, Reject, Neutral)),
    xpendable_anr = dict(expendable = True,
        votes = (Accept, Neutral, Reject, Accept, Neutral, Reject)))
for k, p in sorted(coplayers.items()):
    p['id'] = k
    p['poll_responses'] = len(p['votes']) * [None]
coplayers = coplayers.values()

# Enable this block to show the properties of the matrix of votes
# among the non-expendable coplayers.
if False:
    mat = [cp['votes']
        for x in ('mean3', 'mean2', 'mean1', 'indiff', 'nice1', 'nice2', 'nice3')
        for cp in coplayers
        if cp['id'] == x]
    print 'Totals'
    for votetype in Reject, Neutral, Accept:
        print votetype, sum(1 for row in mat for v in row if v is votetype)
    print ''
    print 'Columns'
    ncol = len(mat[0])
    for votetype in Reject, Neutral, Accept:
        print votetype, ' '.join(
            str(sum(1 for row in mat if row[i] == votetype))
            for i in range(ncol))
    print ''
    print 'Rows'
    from collections import Counter
    for row in mat:
        d = Counter(row)
        print 'R {}, N {}, A {}'.format(d[Reject], d[Neutral], d[Accept])
    exit()

# Decide what order the expendables will be kicked out. We choose
# a random order that will result in the subject getting an equal
# number of each type of vote.
while True:
    kickout_order = shuffled([p for p in coplayers if p['expendable']])
    counts = Counter([vote
        for i, cp in enumerate(kickout_order)
        for vote in cp['votes'][: i + 1]])
    if len(counts.keys()) == len('RNA') and len(set(counts.values())) == 1:
        break
o.save('coplayer_kickout_order', [p['id'] for p in kickout_order])

# Make the coplayers evenly split by gender within the expendable
# and non-expendable groups.
for i, p in enumerate(shuffled([p for p in coplayers if p['expendable']])):
    p['female'] = bool(i % 2)
for i, p in enumerate(shuffled([p for p in coplayers if not p['expendable']])):
    p['female'] = bool(i % 2)
  # Because there's an odd number of non-expendable coplayers,
  # we're left with one more male than we have females. Later,
  # if we learn that the subject is male, we'll make one of
  # the male non-expendables female.

def pronoun_nom(p): return 'she' if p['female'] else 'he'
def pronoun_obj(p): return 'her' if p['female'] else 'him'
def pronoun_gen(p): return 'her' if p['female'] else 'his'

# Assign names and portraits.
males = zip(shuffled(male_names), shuffled(male_portraits))
females = zip(shuffled(female_names), shuffled(female_portraits))
for p in coplayers:
    p['name'], p['portrait'] = females.pop() if p['female'] else males.pop()

portrait_stim_cache = {}
def portrait_stim(x, y, p, border_color = 'black'):
    img = par['subject_portrait_path'] if p is None else image_path(p['portrait'])
    k = x, y, border_color, img
    if k not in portrait_stim_cache:
        portrait_stim_cache[k] = StimGroup((
            ImageStim(o.win, pos = (x, y),
                image = img),
            Rect(o.win, pos = (x, y),
                width = (portrait_dims[0] + 3) / (.5 * o.screen_width),
                height = (portrait_dims[1] + 3) / (.5 * o.screen_height),
                lineColor = border_color, lineWidth = 3)))
    return portrait_stim_cache[k]

# Assign fluff.
for p, age, (hometown, school), interest in zip(
        coplayers, shuffled(ages), shuffled(locations), shuffled(interests)):
    p['fluff'] = dict(
        Age = age, Hometown = hometown, School = school, Interests = interest)
# Make sure universities are only assigned to 18-year-olds.
for p in [p for p in coplayers if
        'University' in p['fluff']['School'] and p['fluff']['Age'] != '18']:
    switch_with = next(p for p in coplayers if
        'University' not in p['fluff']['School'] and p['fluff']['Age'] == '18')
    p['fluff']['School'], switch_with['fluff']['School'] = (
        switch_with['fluff']['School'], p['fluff']['School'])

o.save('coplayers', {p['id']: p for p in coplayers})
  # We don't copy the coplayer-objects because we want later edits
  # (such as the addition of poll responses) to be recorded.

# ------------------------------------------------------------
# * The likability-rating subroutine
# ------------------------------------------------------------

def likability_scale(y):
    rs = RatingScale(o.win, pos = (0, y),
        low = 1, high = 9,
        labels = ['Not at all', 'Somewhat', 'Extremely'],
        textColor = 'black', lineColor = 'black',
        marker = 'circle', markerColor = 'black',
        stretch = 1.75,
        showValue = False, skipKeys = None, scale = None,
        singleClick = True, showAccept = False)
    return rs

def rate_likabilities(time):
    cps = shuffled(coplayers)
    o.save(('likability_ratings', time, 'rating_order'),
        [p['id'] for p in cps])
    for p in cps:
        o.scale_screen(('likability_ratings', time, 'ratings', p['id']),
            portrait_stim(-.5, .5, p),
            o.text(0, .2, 'How much do you like {}?'.format(p['name'])),
            likability_scale(0),
            o.text(0, -.5, 'How much do you think other people would like {}?'.format(pronoun_obj(p))),
            likability_scale(-.7))

# ------------------------------------------------------------
# * The voting subroutine
# ------------------------------------------------------------

icon_dim = 200 # Pixels
icon_thickness = 10 # Pixels

def icon_frame(x, color):
    kw = dict(units = 'pix', fillColor = color, lineColor = color)
    return [
        Rect(o.win, icon_dim, icon_thickness,
            pos = (x, icon_dim/2 - icon_thickness/2), **kw),
        Rect(o.win, icon_dim, icon_thickness,
            pos = (x, -icon_dim/2 + icon_thickness/2), **kw),
        Rect(o.win, icon_thickness, icon_dim,
            pos = (x + icon_dim/2, 0), **kw),
        Rect(o.win, icon_thickness, icon_dim,
            pos = (x - icon_dim/2, 0), **kw)]

def reject_icon(x = 0):
    return ImageStim(o.win, pos = (x, 0),
        image = image_path('thumbs-down.png'))
Reject.icon_c = reject_icon()

def accept_icon(x = 0):
    return ImageStim(o.win, pos = (x, 0),
        image = image_path('thumbs-up.png'))
Accept.icon_c = accept_icon()

def neutral_icon(x = 0):
    return Rect(o.win, width = .25, height = .5, pos = (x, 0),
        fillColor = 'yellow',
        lineColor = 'gray', lineWidth = 10)
Neutral.icon_c = neutral_icon()

voting_time_limit = 5  # In seconds

def voting(nround):

    practice = nround is None
    if practice:
        cps = [
            dict(id = 'practice_a',
                 name = 'Player A', female = False,
                 portrait = 'example-male.png',
                 vote = Accept),
            dict(id = 'practice_b',
                 name = 'Player B', female = True,
                 portrait = 'example-female.png',
                 vote = Reject)]
    else:
        cps = shuffled(coplayers)
        o.save('vote_order', [p['id'] for p in cps])
    with blank_background:
      for i, p in enumerate(cps):

        # The subject votes.
        stimuli = [
            portrait_stim(-.5, .5, p, border_color = 'white'),
            o.html(.2, .8, vAlign = 'top', color = 'white', font_size = 14, string =
                # Show everything the subject knows about this
                # coplayer, except for observed voting behavior.
                p['name'] + "<br><br>" +
                '<b>{}</b><br>'.format('Female' if p['female'] else 'Male') +
                ('' if practice else '<br>'.join(
                    ['<b>{}:</b> {}'.format(k, escape(p['fluff'][k])) for k in
                        ['Age', 'Hometown', 'School', 'Interests']] +
                    ['<b>{}:</b> {}'.format(
                            escape(r['question']),
                            escape(p['poll_responses'][i + 1]))
                        for i, r in enumerate(round_descriptions)
                        if i + 1 <= nround])))]
        voting_timer = CountdownTimer(voting_time_limit)
        o.keypress_screen(('subject_votes', p['id']),
            {
               voting_timer: TriggerKey('Neutral', None if practice else
                   trigger_code(p, 'subject_votes_neutral')),
               Reject.key: TriggerKey('Kick\nOut', None if practice else
                   trigger_code(p, 'subject_votes_to_reject')),
               Accept.key: TriggerKey('Keep', None if practice else
                   trigger_code(p, 'subject_votes_to_accept'))},
            o.text(0, -.5, color = 'white', wrap = 2, string =
                'Should we keep {} or kick {} out?'.format(
                    p['name'], pronoun_obj(p))),
            o.text(-.25, -.7, color = 'white', string =
                '{} - Kick Out'.format(Reject.key)),
            o.text(.25, -.7, color = 'white', string =
                '{} - Keep'.format(Accept.key)),
            *stimuli)
        o.wait_screen_till(voting_timer,
            o.text(0, -.5, color = 'white', wrap = 2, string =
                'Vote registered'),
            *stimuli)

        # Show a fixation cross.
        o.wait_screen(1, o.fixation_cross)

        # Now show the coplayer's vote.
        pv = p['vote'] if practice else p['votes'][nround]
        if not practice: o.trigger(trigger_code(p, {
            Reject: 'subject_gets_reject_vote',
            Neutral: 'subject_gets_neutral_vote',
            Accept: 'subject_gets_accept_vote'}[pv]))
        o.wait_screen(2, pv.icon_c)
        o.wait_screen(1.5)

    if not practice:
      # An expendable coplayer is ousted.
        loser = kickout_order[nround]
        coplayers.remove(loser)
        o.okay_screen('loser',
            portrait_stim(0, .5, loser),
            o.text(0, -.2, "And it's final decision time. Looks like {} got the least points! {} journey ends here. You get to continue on to the next island!".format(
                loser['name'],
                pronoun_gen(loser).capitalize())))

# ------------------------------------------------------------
# * Preliminaries
# ------------------------------------------------------------

if par['debug']:
    o.data['subject'] = 'test'
else:
    o.get_subject_id('Island Getaway')

subject_name = '???'

o.start_clock()

# ------------------------------------------------------------
# * Introduction
# ------------------------------------------------------------

with background('Hawaje-NoRedLine.jpg'):
    message(2, 'Aloha!')

    with o.dkey_prefix('introduction'):

        o.instructions('set_the_scene', "Let's pretend you've just landed on the Hawaiian Island of Niihau to begin a summer vacation with a group of {} other teens. But the journey isn't over yet! First, you must make your way along the islands to get to the Big Island of Hawaii. Once there, your vacation will begin!".format(
            len(coplayers)))

        o.instructions('game_overview', "As you travel along the islands, you'll get to know more and more about the other players. After each round, you'll vote for who you would like to continue on to the Big Island with you and who you would like to send home. But the other players will also be voting on you! And your goal is to stay in the game and be one of the {} players (out of the original {}) who make it to the Big Island!".format(
            len(coplayers) + 1 - (len(round_descriptions) + 1),
            len(coplayers) + 1))

    with o.dkey_prefix('profile'):

        o.text_entry_screen('gender', 'Now you can fill out your profile.\n\nWhat is your gender?')
        o.data['profile']['gender'] = simplify_gender(o.data['profile']['gender'])
        if o.data['profile']['gender'] == 'Male':
            # Make a male non-expendable female so that there's
            # of equal number of male and female players.
            transgal = choice([p for p in coplayers if not p['female']])
            transgal['female'] = True
            transgal['name'] = choice(female_names - {p['name'] for p in coplayers if p['female']})
            transgal['portrait'] = choice(female_portraits - {p['portrait'] for p in coplayers if p['female']})

        o.text_entry_screen('name', 'What is your first name?')
        subject_name = o.data['profile']['name']
        # Try to normalize capitalization.
        if subject_name.isalpha() and (
                subject_name.islower() or
                    (len(subject_name) > 2 and subject_name.isupper())):
                      # Don't downcase "AJ".
            subject_name = subject_name.lower().capitalize()
        # If the subject's name exactly matches the name of a
        # coplayer (case-insensitively), rename the coplayer.
        try:
            p = next(p for p in coplayers if
                p['name'].lower() == subject_name.lower())
            p['name'] = extra_female_name if p['female'] else extra_male_name
        except StopIteration:
            pass

        o.nonneg_int_entry_screen('age', 'How old are you?')

        o.text_entry_screen('hometown', 'What is your hometown?')

        o.text_entry_screen('school', 'What school do you go to?')

        o.text_entry_screen('interests', "What are some things you're interested in?")

        o.okay_screen('view',
            portrait_stim(0, .5, None),
            o.html(0, 0,
                subject_name + "<br><br>" +
                '<b>{}</b><br>'.format(o.data['profile']['gender']) +
                '<br>'.join(
                    '<b>{}:</b> {}'.format(k.capitalize(), escape(o.data['profile'][k])) for k in
                        ['age', 'hometown', 'school', 'interests'])))

    # Don't keep the profile data due to IRB shenanigans (for
    # the Kujawa lab at Penn State).
    del o.data['profile']

    lag(3)

# Now that the coplayers' genders are set, we can assign trigger
# codes.
seen_genders = [0, 0]
for p in coplayers:
    p['trigger_id'] = seen_genders[p['female']]
    seen_genders[p['female']] += 1

write('intro')

# ------------------------------------------------------------
# * Round 0
# ------------------------------------------------------------

with o.dkey_prefix(('round', 0)), background('Niihau_sep_2007.jpg'):

    message(round_wait, 'Round 1: Niihau')

    o.instructions('read_profiles', 'Take a moment to learn about the other players.')

    cps = shuffled(coplayers)
    o.save('profile_order', [p['id'] for p in cps])
    for i, p in enumerate(cps):
        o.okay_screen(('fluff', i),
            portrait_stim(0, .5, p),
            o.html(0, 0,
                p['name'] + "<br><br>" +
                '<b>{}</b><br>'.format('Female' if p['female'] else 'Male') +
                '<br>'.join(
                    '<b>{}:</b> {}'.format(k, escape(p['fluff'][k])) for k in
                        ['Age', 'Hometown', 'School', 'Interests'])))

    rate_likabilities('pre')

    o.instructions('voting_begins', html = True, string = "And on to the first round of voting. Who do you want to send home? And who do you want to continue with you on to the next island? You can vote to keep or send home as many other players as you want, but you have to vote to send <b>at least one</b> other player home. Whoever gets the most votes to be sent home will be kicked off the island, with ties broken randomly.<br><br>Each time you vote, you will then find out how that player voted for you.")

    o.okay_screen('feedback_explanation',
        o.text(0, .7, "For each player, after you've made your own vote, you'll see an icon that shows their vote."),
        accept_icon(-.4),
        o.text(-.4, -.3, "This means a vote to keep you.",
            vAlign = 'top', wrap = .6),
        reject_icon(.4),
        o.text(.4, -.3, "This means a vote to kick you out.",
            vAlign = 'top', wrap = .6))

    with o.dkey_prefix('voting_practice'):
        o.instructions('intro', "First, you'll see two examples of how voting works.")
        voting(None)
        o.instructions('done', 'Now for the first round of real voting.')

    voting(0)
    write('voting-round-0')

# ------------------------------------------------------------
# * All other rounds
# ------------------------------------------------------------

for i, r in enumerate(round_descriptions):
    nround = i + 1
    with o.dkey_prefix(('round', nround)), background(r['background']):

        message(round_wait, 'Round {}: {}'.format(nround + 1, r['place']))
        o.instructions('fluff', r['fluff'])

        o.text_entry_screen('poll_question',
            "Now you'll all answer another question so you can get to know each other better.\n\n" +
            r['question'])

        for p, resp in zip(coplayers, shuffled(r['responses'])):
            p['poll_responses'][nround] = resp
        varwait = max(expovariate(2) for _ in coplayers)
        o.save('poll_varwait', varwait)
        lag(varwait)

        responses = shuffled(
            [(p['id'], p['name'], p['poll_responses'][nround]) for p in coplayers] +
            [('SUBJECT', subject_name, o.data['round'][nround]['poll_question'])])
        o.save('poll_response_order', [r[0] for r in responses])
        o.okay_screen('poll_results',
            o.text(0, .8, "Here are your responses:"),
            o.text(0, .65,
                "\n".join(["{}: {}".format(r[1], r[2]) for r in responses]),
                wrap = 1.4, vAlign = 'top'))

        voting(nround)
        write('voting-round-' + str(nround))

# ------------------------------------------------------------
# * A winner is you!
# ------------------------------------------------------------

with background('Rainbow_over_palms_at_Big_Island_of_Hawaii.jpg'):
    message(3, 'You made it to the Big Island of Hawaii!\nLet the vacation begin!')

    rate_likabilities('post')

# ------------------------------------------------------------
# * Post-game questionnaire
# ------------------------------------------------------------

refuse = 'I prefer not\nto answer'
scale_levels = ('Not at all', 'Slightly', 'Somewhat', 'Quite a lot', 'Extremely', refuse)
na_scale_level = scale_levels.index(refuse) + 1

o.questionnaire_screen('postgame_questionnaire', 'In the below questionnaire, pick the options that best represent the feelings you were experiencing during the game.',
    prompt_color = 'white',
    scale_levels = scale_levels,
    font_size = 12,
    column_filler_width = 80,
    questions = [
        {'id': ('belonging', 1), 'text': "I felt I didn't fit in with the others."},
        {'id': ('other', 1), 'text': 'It bothered me to vote off other players.'},
        {'id': ('self-esteem', 2), 'text': 'My self-esteem was high.'},
        {'id': ('task disengagement', 5), 'text': 'I really wanted to stay in the game.'},
        {'id': ('self-esteem', 3), 'text': 'I felt liked.'},
        {'id': ('self-esteem', 4), 'text': 'I felt unsure of myself.'},
        {'id': ('belonging', 5), 'text': 'I felt the other players wanted me to continue on to the Big Island.'},
        {'id': ('preoccupation with exclusion', 1), 'text': 'I wondered "Why did they vote me off?"'},
        {'id': ('task disengagement', 2), 'text': 'After a while I lost interest in staying in the game.'},
        {'id': ('survivor', 1), 'text': 'It bothered me to vote off other players.'},
        {'id': ('belonging', 2), 'text': 'I felt rejected.'},
        {'id': ('belonging', 4), 'text': 'I felt I belonged to the group.'},
        {'id': ('survivor', 2), 'text': 'I wondered why other players voted me off.'},
        {'id': ('meaningful existence', 4), 'text': 'I felt important.'},
        {'id': ('control', 4), 'text': 'I felt I was unable to influence the action of others.'},
        {'id': ('task disengagement', 3), 'text': "I would've liked to play this game again."},
        {'id': ('control', 2), 'text': 'I felt I had control over the course of the game.'},
        {'id': ('self-esteem', 1), 'text': 'I felt good about myself.'},
        {'id': ('meaningful existence', 2), 'text': "I felt I didn't matter."},
        {'id': ('control', 1), 'text': 'I felt powerful.'}])

# "I prefer not to answer" values are set to "NA".
for rs in o.data['postgame_questionnaire'].values():
   for i, r in enumerate(rs):
       if r == na_scale_level:
           rs[i] = 'NA'

# ------------------------------------------------------------
# * Done!
# ------------------------------------------------------------

o.done()
write('done')

o.wait_screen(1,
    o.text(0, 0, color = 'white', string = 'Done!\n\nPlease let the experimenter know you are done.'))
